# Generated by Django 6.0.5 on 2026-08-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('budget', models.PositiveIntegerField()),
                ('menu', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('advance_amount', models.PositiveIntegerField(default=50000)),
                ('booking_status', models.CharField(default='Confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
