# Generated by Django 6.0.5 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
